import 'package:flutter/material.dart';
import 'package:hive/hive.dart';
Future<void> zapiszKolorDoSkrzynki(Color nowyKolor,Color nowyKolor2,Color nowykolor3) async {
  final box = await Hive.openBox<Color>('colorsBox'); // Utwórz skrzynkę dla kolorów

  await box.put(0, nowyKolor);
  await box.put(1, nowyKolor2);
  await box.put(2, nowykolor3);
  await box.close();
}

List<Color> listaKolorow = [
  Colors.red.shade900,
  Colors.green.shade900,
  Colors.blue.shade900,
  Colors.yellow.shade900,
  Colors.black,
  Colors.white,
  Colors.grey.shade900,
  Colors.orange.shade900,
  Colors.pink.shade900,
  Colors.brown.shade900,
  Colors.purple.shade900,
  Colors.indigo.shade900,
  Colors.cyan.shade900,
  Colors.teal.shade900,
  Colors.lime.shade900,
  Colors.amber.shade900,
  Colors.deepOrange.shade900,
  Colors.lightBlue.shade900,
  Colors.lightGreen.shade900,
  Colors.blueGrey.shade900,
];

List<Color> listaKolorow2 = [
  Colors.red.shade100,
  Colors.green.shade100,
  Colors.blue.shade100,
  Colors.yellow.shade100,
  Colors.black,
  Colors.white,
  Colors.grey.shade100,
  Colors.orange.shade100,
  Colors.pink.shade100,
  Colors.brown.shade100,
  Colors.purple.shade100,
  Colors.indigo.shade100,
  Colors.cyan.shade100,
  Colors.teal.shade100,
  Colors.lime.shade100,
  Colors.amber.shade100,
  Colors.deepOrange.shade100,
  Colors.lightBlue.shade100,
  Colors.lightGreen.shade100,
  Colors.blueGrey.shade100,
];
List<Color> listaKolorow3 = [

  Colors.red,
  Colors.green,
  Colors.blue,
  Colors.yellow,
  Colors.black,
  Colors.white,
  Colors.grey,
  Colors.orange,
  Colors.pink,
  Colors.brown,
  Colors.purple,
  Colors.indigo,
  Colors.cyan,
  Colors.teal,
  Colors.lime,
  Colors.amber,
  Colors.deepOrange,
  Colors.lightBlue,
  Colors.lightGreen,
  Colors.blueGrey,
];

List<String> nazwyKolorow = [
  "red",
  "green",
  "blue",
  "yellow",
  "black",
  "white",
  "grey",
  "orange",
  "pink",
  "brown",
  "purple",
  "indigo",
  "cyan",
  "teal",
  "lime",
  "amber",
  "deepOrange",
  "lightBlue",
  "lightGreen",
  "blueGrey",
];
// List<Color> listaKolorow = [
//   Colors.red,
//   Colors.green,
//   Colors.blue,
//   Colors.yellow,
//   Colors.black,
//   Colors.white,
//   Colors.grey,
//   Colors.orange,
//   Colors.pink,
//   Colors.brown,
//   Colors.purple,
//   Colors.indigo,
//   Colors.cyan,
//   Colors.teal,
//   Colors.lime,
//   Colors.amber,
//   Colors.deepOrange,
//   Colors.lightBlue,
//   Colors.lightGreen,
//   Colors.cyan,
//   Colors.amber,
//   Colors.brown,
//   Colors.grey,
//   Colors.blueGrey,
//   Colors.amber,
//   Colors.orange,
//   Colors.deepPurple,
//   Colors.pink,
//   Colors.teal,
//   Colors.yellow,
//   Colors.lime,
//   Colors.blueAccent,
//   Colors.greenAccent,
//   Colors.amberAccent,
//   Colors.redAccent,
//   Colors.lightBlueAccent,
//   Colors.lightGreenAccent,
//   Colors.cyanAccent,
//   Colors.deepOrangeAccent,
//   Colors.blueGrey,
//   Colors.indigo,
//   Colors.purple,
//   Colors.deepPurpleAccent,
//   Colors.pinkAccent,
//   Colors.brown,
//   Colors.grey,
//
// ];
// List<Color> listaKolorow2 = [
//   Colors.red.shade100,
//   Colors.green.shade100,
//   Colors.blue.shade100,
//   Colors.yellow.shade100,
//   Colors.black,
//   Colors.white,
//   Colors.grey.shade100,
//   Colors.orange.shade100,
//   Colors.pink.shade100,
//   Colors.brown.shade100,
//   Colors.purple.shade100,
//   Colors.indigo.shade100,
//   Colors.cyan.shade100,
//   Colors.teal.shade100,
//   Colors.lime.shade100,
//   Colors.amber.shade100,
//   Colors.deepOrange.shade100,
//   Colors.lightBlue.shade100,
//   Colors.lightGreen.shade100,
//   Colors.cyan.shade100,
//   Colors.amber.shade100,
//   Colors.brown.shade100,
//   Colors.grey.shade100,
//   Colors.blueGrey.shade100,
//   Colors.amber.shade100,
//   Colors.orange.shade100,
//   Colors.deepPurple.shade100,
//   Colors.pink.shade100,
//   Colors.teal.shade100,
//   Colors.yellow.shade100,
//   Colors.lime.shade100,
//   Colors.blueAccent.shade100,
//   Colors.greenAccent.shade100,
//   Colors.amberAccent.shade100,
//   Colors.redAccent.shade100,
//   Colors.lightBlueAccent.shade100,
//   Colors.lightGreenAccent.shade100,
//   Colors.cyanAccent.shade100,
//   Colors.deepOrangeAccent.shade100,
//   Colors.blueGrey.shade100,
//   Colors.indigo.shade100,
//   Colors.purple.shade100,
//   Colors.deepPurpleAccent.shade100,
//   Colors.pinkAccent.shade100,
//   Colors.brown.shade100,
//   Colors.grey.shade100,
//
// ];
// List<String> nazwyKolorow=[
// "red",
// "green",
// "blue",
// "yellow",
// "black",
// "white",
// "grey",
// "orange",
// "pink",
// "brown",
// "purple",
// "indigo",
// "cyan",
// "teal",
// "lime",
// "amber",
// "deepOrange",
// "lightBlue",
// "lightGreen",
// "cyan",
// "amber",
// "brown",
// "grey",
// "blueGrey",
// "amber",
// "orange",
// "deepPurple",
// "pink",
// "teal",
// "yellow",
// "lime",
// "blueAccent",
// "greenAccent",
// "amberAccent",
// "redAccent",
// "lightBlueAccent",
// "lightGreenAccent",
// "cyanAccent",
// "deepOrangeAccent",
// "blueGrey",
// "indigo",
// "purple",
// "deepPurpleAccent",
// "pinkAccent",
// "brown",
// "grey",
//
// ];